### ISSUE TITLE
Floating Tree After Tree punching

### ISSUE THREAD

**Issue by jamierholt** [jaltekruse/WhatEverYouWantMinecraft#27]
Description: After using tree punching to collect wood, the wood block from the tree disappears and the tree is essentially "floating" above where the block used to be.

Severity: Low (It's actually kinda funny having floating trees in the game, although not realistic)

Suggestion: Don't Have the block disappear, but still allow the user to collect wood, that way the tree remains

**Comment by wreardan** [comment]
This is the default behavior in Minecraft which is not changed with our Mod.  Though maybe an interesting idea would be to have the tree automatically harvest at the bottom when your Treepunching gets high enough.

**Comment by jamierholt** [comment]
Didn't know that haha. I've never actually played minecraft before, I was just assuming that it wasn't supposed to do that. I think some sort of function where the tree would fall or something if you knock out the bottom three blocks would be kinda cool. Just a brainstorm thought.
