### ISSUE TITLE
Zombie Doesnt Appear

### ISSUE THREAD

**Issue by jamierholt** [jaltekruse/WhatEverYouWantMinecraft#30]
Description: Trying to use the Summon zombie method and a zombie doesn't appear. Waited in the same place in case a zombie was going come moving towards me and no zombie appeared either.

Severity: Severe to the function, Moderate to the overall Mod

Suggestion: If there is a requirement for the summoning of a zombie, make sure the player knows. Otherwise, make the zombie spawn where the user summons them.

**Comment by wreardan** [comment]
fixed in commit ee64b7cf1da077b8ffa24aca59def51a7bd8605d
