### ISSUE TITLE
Holy hand grenade not functional

### ISSUE THREAD

**Issue by Pirolf** [jaltekruse/WhatEverYouWantMinecraft#32]
Desc: found holy hand grenade in inventory in creative mode. when using it, it does nothing except sing a holy song

Severity: low

Suggestion: if it's only use is to sing a song, then add a brief description to the item, so that when user hovers on item, they know what it does. Or if it's not supposed to work this way, make it work

**Comment by wreardan** [comment]
This issue was fixed in commit c15f8c04119c5f5929bb49c03ff71fcd88f25a6c
There was an erroneous rotate in the code causing it to rotate 180 degrees.
