### ISSUE TITLE
Error in console when Script GUI is brought up

### ISSUE THREAD

**Issue by katamaritaco** [jaltekruse/WhatEverYouWantMinecraft#33]
Not sure if it really affects anything, but I figured I'd post it.

This error occurs when 'I' is pressed and the ScriptGUI is brought up:
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider scala.tools.nsc.interpreter.IMain$Factory not found

**Comment by wreardan** [comment]
It doesn't affect anything. It seems to happen once when the ScriptEngine is initialized.  Not sure what causes it but I have seen it a lot as well.
